spring:
  datasource:
    url: jdbc:postgresql://intranet3:5432/development?currentSchema=books
    username: books
    password: rJ12pw83T8
    jpa: show-sql=true

oauth:
  baseUrl: https://intranet3.softsystem.pl/oauth

notifications:
  prodEnabled: false
  clientPassword: Kb6q6ccbpc3EsGkmsUi6zuqkV2xyPcWb2hyQHLWjiSqea
  url: https://intranet3.softsystem.pl/mails-console
  devRecipients: dsowins@softsystem.pl
  id:
    testNotification: 204
    reservationNotification: 205
    remindNotification: 206
